### ISSUE TITLE
0.2.6 release on PyPI does not match code on Github

### ISSUE THREAD

**Issue by eli-schwartz** [dephell/dephell_discover#4]
The last commit on Github was updating the version number in pyproject.toml to 0.2.5 -- where is 0.2.6 from and what does it change?

**Comment by orsinium** [comment]
0.2.5 was builded by the old dephell, and package is broken (contains `-` in dist-info folder name). 0.2.6 fixes only this. It's kind of post-release, but semver doesn't support post-releases. I forgot to push it, I'll do it today. Thank you :)

**Comment by orsinium** [comment]
Pushed :)
https://github.com/dephell/dephell_discover/commit/66c4bc272abd499e7bcdb6b8044a60da93abf66c

**Comment by eli-schwartz** [comment]
Thanks.

**Comment by orsinium** [comment]
@eli-schwartz, are you updating all packages in arch by hand? Can we automate builds?

**Comment by eli-schwartz** [comment]
There are tools to bump version numbers and regenerate checksums, so the update process is fairly seamless. In some cases, like dephell 0.7.3 => 0.7.4, the testsuite failed (the packaging script is configured to automatically run unittests) until I updated the build manifest to add the new dev-dependencies.

That being said, yes, the build is ultimately kicked off manually and I may hold off the release until I did basic smoketests.

...

The source of this issue report was when I tried updating to the new dephell version because I was flagged about the new version, but trying to run the updated dephell package failed because of outdated dephell_discover (which I was not flagged about.)

I'm subscribed to Github's "watch releases" feature, which is one reason why I like tagged releases in git -- it makes it a lot easier to know immediately when there is an available update.

It's also possible to mark a package as out of date via our packages web interface (if this is flagged, then the developer dashboard will add it to my TODO list):
- search results: https://www.archlinux.org/packages/?q=python-dephell
- package details: https://www.archlinux.org/packages/community/any/python-dephell/
- "Flag Package Out-of-Date" button on the right: https://www.archlinux.org/packages/community/any/python-dephell/flag/

There are also community tools like https://repology.org/projects/?search=dephell but repology depends on finding a package available in a Linux distro, and so far I am the only one packaging dephell so it only knows about the version available in Arch.

**Comment by orsinium** [comment]
Oh, great. If everything ok, next release will be with vendorized dependencies. So, all build will be much easier.

https://github.com/dephell/dephell/issues/109
https://github.com/dephell/dephell/issues/51
https://github.com/dephell/dephell/tree/vendorize

**Comment by eli-schwartz** [comment]
Builds are actually pretty easy at the moment as long as I get flagged for the update.

Distribution policy says I cannot use vendored dependencies, though, so I'd need to figure out a way to disable that.

**Comment by orsinium** [comment]
Hmm, good point, I'll see how to achieve this.
